version: 2.1

orbs:
  node: circleci/node@2.1.1

commands:
  generate_package:
    description: generate package from Protobuf definitions
    parameters:
      language:
        type: string
    steps:
      - attach_workspace:
          at: workspace
      - run:
          name: Generating for << parameters.language >> package
          command: |
            entrypoint.sh -o workspace/generated/<< parameters.language >>/ -l << parameters.language >> -f kohi/**/*.proto
            ls -R workspace/generated/<< parameters.language >>
      - persist_to_workspace:
          root: workspace
          paths:
            - generated/<< parameters.language >>
  git_diff:
    description: generate Git Diff
    parameters:
      language:
        type: string
    steps:
      - attach_workspace:
          at: workspace
      - run:
          name: Generate Git Diff
          command: |
            git config --global user.name "Kohi Bot"
            git config --global user.email "kelvintaywl@gmail.com"
            git clone --depth=1 https://kelvintaywl:$CI_GITHUB_TOKEN@github.com/kelvintaywl/kohi_<< parameters.language >>.git
            cp -r workspace/generated/<< parameters.language>>/kohi kohi_<< parameters.language >>/lib
            cd kohi_<< parameters.language >>
            # export CUR_VERSION=$(git tag -l --sort=-v:refname | head -n 1)
            export CUR_VERSION=0.0.1
            # export CUR_VERSION=$(npx semver -c $CUR_VERSION)
            export VERSION=0.1.0
            # # TODO: fix this for different languages (assumption: ruby gem)
            sed -i "s/'$CUR_VERSION'/'$VERSION'/" lib/kohi/version.rb
            git add .
            git commit -m "[automated] feat: library upgrade to $VERSION"
            git tag -a "v$VERSION" -m "[automated] release $VERSION"
            git log -n 1
            git push --tags -u origin master

jobs:
  proto:
    docker:
      - image: bufbuild/buf
    steps:
      - checkout
      - run: buf check lint
  publish:
    docker:
      - image: namely/protoc-all
    steps:
      - checkout
      - generate_package:
          language: ruby
      # - generate_package:
      #     language: python

  diff:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - node/install:
          node-version: 'lts'
      - node/install-packages
      - git_diff:
          language: ruby

workflows:
  validation:
    jobs:
      - proto
  release:
    jobs:
      - proto
      - publish:
          requires:
            - proto
      - diff:
          context: github_ci
          requires:
            - publish
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
